# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post', 'Can post to JoonaBlagV2'),)},
        ),
    ]
