# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0002_auto_20170506_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('can_comment', 'Can comment on JoonaBlagV2'), ('can_vote_comments', 'Can vote on comments')),
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post', 'Can post to JoonaBlagV2'), ('can_vote_posts', 'Can vote on posts'))},
        ),
    ]
