# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0003_auto_20170506_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
