# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0004_comments_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
