# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0005_auto_20170506_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
