# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0006_auto_20170506_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_comment', 'Can comment'), ('can_vote_comments', 'Can vote on comments'))},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post', 'Can post'), ('can_vote_posts', 'Can vote on posts'), ('can_upload', 'Can upload files'))},
        ),
    ]
