# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0008_auto_20170506_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=0),
        ),
    ]
