# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoonaBlagV2', '0010_auto_20170506_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
